### ISSUE TITLE
Endpoints Entrega 3

### ISSUE THREAD

**Issue by FernaMera** [hhrib/tacs-tp#23]
- [x] post de gauchos para mover entre municipios

- [x] post /municipios/atacar --- devolver estado a todos --- ver websockets?

- [x] patch de municipios para modifacar la especializacion entre prod y def

- [x] get para estadisticas -- ver websockets? -> EDIT: No es websockets, quedamos que triggerea el cliente las estadísticas.

**Comment by tachucj** [comment]
El patch de municipios terminó siendo un patch a Matches. En realidad estamos modificando el estado interno de una partida. No de los municipios persistidos.

Queda pendiente pasar el Post de gauchos del controller de municipios al controller de partidas. Por la misma razón.

**Comment by FernaMera** [comment]
fe287507d15bc0cdd38b02321224de1d3ce38916
