### ISSUE TITLE
API REST: Saber si un usuario ya está en una partida

### ISSUE THREAD

**Issue by Jaugustopose** [hhrib/tacs-tp#26]
Se envía una solicitud http a un endpoint _(a definir)_ para saber si un jugador ya se encuentra en una partida activa.

EDIT Ale:
Se devolverá el matchId de la partida en la que está anotado el usuario (JSON)
Si no estuviera en ninguna partida se devolverá Not Found.

**Comment by tachucj** [comment]
Hecho.
![GetMatchForUser-OK](https://user-images.githubusercontent.com/7362431/95372319-c73f9a80-08b1-11eb-8a10-d49e831eb53c.PNG)
![GetMatchForUser-NOT_FOUND](https://user-images.githubusercontent.com/7362431/95372325-c870c780-08b1-11eb-9f71-602e65a25dee.PNG)
