### ISSUE TITLE
Muchos If anidados?

### ISSUE THREAD

**Issue by FernaMera** [hhrib/tacs-tp#33]
Esto es un tema de gustos, pero con métodos con mucha validación yo prefiero siempre ir descartando los escenarios de error, tirando excepción y dejando al final el código limpio del caso donde se dan todas las precondiciones. Sino hay if anidados y el código se hace más difícil de seguir.

"Imagen de Ryu tirando un Hadouken al codigo"

**Comment by tachucj** [comment]
Se refiere sí a los if anidados, a no ir verificando todas las condiciones y si pasa la primera verificar la otra en un else. Igual no sé a qué parte específicamente se refiere donde haya ese encadenamiento de if-elses. Pero a lo que apunta que aspiremos es algo así supongo:
![image](https://user-images.githubusercontent.com/7362431/95695219-562f1880-0c0c-11eb-8934-9ffeb57beb81.png)

Todas las condiciones de error primero y en if distintos, "tirando excepción" dice, acá usamos una variante de eso que acumula los errores y al final chequea que esa lista de errores tenga algo y tira una excpeción de una con todos, pero básicamente es la misma idea.

**Comment by FernaMera** [comment]
Refactor: a248f7114453c1a8bfc47ef7e628af2d7902db58
