### ISSUE TITLE
Mejorar Respuesta al Atacar un Municipio

### ISSUE THREAD

**Issue by FernaMera** [hhrib/tacs-tp#34]
No me copa mucho que #Municipality.attack devuelva un int como código de retorno. Que quieren representar? Hay una forma mejor de hacerlo?

**Comment by Jaugustopose** [comment]
Preguntarle por mail a Seba qué quiso decir, cómo sería una forma más elegante de laburarlo.

**Comment by FernaMera** [comment]
Refactor: a248f7114453c1a8bfc47ef7e628af2d7902db58
