### ISSUE TITLE
Usar Patron State para estados de municipios

### ISSUE THREAD

**Issue by FernaMera** [hhrib/tacs-tp#36]
#Municipality.produceGauchos Revisen el patrón state por favor.

**Comment by tachucj** [comment]
Acá decía patron State. Son bastante parecidos pero no es exactamente lo mismo. Decía State. Updateo el issue.

**Comment by FernaMera** [comment]
Se que decia State, pero no me pareció que iba en este caso hasta que me puse a hacerlo...

**Comment by FernaMera** [comment]
9699664ea7dc5d17ee60bd903c0a7052eb4c4e11
