### ISSUE TITLE
Backend - User stories 2

### ISSUE THREAD

**Issue by Jaugustopose** [hhrib/tacs-tp#6]
Partidas, se debe:

- Generar nuevas partidas seleccionando provincia, cantidad de municipios a usar y usuarios participantes (y por lo tanto buscar usuarios)
- Listar todas las partidas, buscar, ordenarlas y filtrar por: fecha, estado
- Modificar estado de una partida (en juego, terminada)
- Cada partida se da sobre un mapa, el mismo es una provincia de argentina a seleccionar.

**Comment by FernaMera** [comment]
Crear Partidas: https://github.com/hhrib/tacs-tp/commit/938b1009986077dde70aa4c7dc5534653b5b80fa
Buscar Paridas: https://github.com/hhrib/tacs-tp/commit/17ea56b496e861db2c1fc88c1ca2d9d23c0e87b6
